name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup
        run: make setup
      
      - name: Run Spellcheck
        run: npm run spellcheck