name: 'Check spelling'
on: # rebuild any PRs and main branch changes
  pull_request:

permissions:
  id-token: write
  contents: write

jobs:
  quality-gates: # run the action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup
        run: make setup
      
      - name: Run Spellcheck
        run: npm run spellcheck

      - name: Run Linting
        run: npm run lint-markdown

      - name: Run Tests
        run: ./scripts/test_all.sh